# Generated by Django 5.2.6 on 2025-09-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasaDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.casadecambio')),
            ],
            options={
                'db_table': 'cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
