# Generated by Django 5.2.6 on 2025-09-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_de_cambio', models.CharField(max_length=255)),
                ('compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cotizaciones',
            },
        ),
    ]
