# Generated by Django 5.2.6 on 2025-09-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casadecambio',
            table='casas_de_cambio',
        ),
    ]
